# fly.toml app configuration file generated for octane-api on 2026-04-28T10:31:53+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'octane-api'
primary_region = 'sin'

[build]

[env]
  CORS_ORIGINS = 'https://octane-smoky.vercel.app,https://octane-app.fly.dev'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
